eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

server:
  port: 8764

spring:
  application:
    name: service-zuul
  profiles:
    active: dev

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
zuul.prefix: /v1