server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
      label: master
      server:
        git:
          uri: ***
          searchPaths: .
          username: ***
          password: ***